harden the sample application
Bandwidth/bandwidth-android pull request #16
Opened 2021-09-14 19:47 UTC by smckinnon-bw

Changes a few things...
- app no longer tries to overlay multple video streams on the same window
- app no longer crashes on departure of an audio stream in the conference
- app uses 'demo' conference
- app no longer crashes on rotate (rotate is disabled)
- app manages all participants and replaces participants when others leave.

Some improvements are still possible

2021-09-14 19:54 UTC, psherk-bw approved these changes

2021-09-14 20:24 UTC, hamermike requested changes

2021-09-14 20:24 UTC, hamermike commented on app/src/main/java/com/bandwidth/android/MainActivity.java
> +        videoCapturer.startCapture(640, 480, 20);
@smckinnon-bw did you mean to update the frames to 20 from 30? No problem if so.

2021-09-22 21:50 UTC, smckinnon-bw commented on app/src/main/java/com/bandwidth/android/MainActivity.java
> +        videoCapturer.startCapture(640, 480, 20);
yup - intentional after a little fiddling with bandwidth.  Not a big deal either way.

2021-09-22 21:52 UTC, smckinnon-bw commented
@hamermike - did I address all the issues?

2021-09-23 13:05 UTC, hamermike approved these changes

2021-09-23 16:54 UTC, merged